name: weather_app
description: An app that displays the weather in Paris over 5 days
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  mocktail: ^0.3.0
  dio: ^4.0.6
  get_it: ^7.2.0
  material_design_icons_flutter: ^6.0.7096
  flutter_bloc: ^8.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  fonts:
    - family: SF-Pro
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Bold.otf
          weight: 800
        - asset: assets/fonts/SF-Pro-Display-BoldItalic.otf
          weight: 800
        - asset: assets/fonts/SF-Pro-Display-Light.otf
          weight: 600
        - asset: assets/fonts/SF-Pro-Display-LightItalic.otf
          weight: 600
        - asset: assets/fonts/SF-Pro-Display-Regular.otf
          weight: 500
        - asset: assets/fonts/SF-Pro-Display-RegularItalic.otf
          weight: 500
        - asset: assets/fonts/SF-Pro-Display-Ultralight.otf
          weight: 400
        - asset: assets/fonts/SF-Pro-Display-UltralightItalic.otf
          weight: 400
        
